name: Build and release

on:
  push:
    branches: [ release ]

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v2
        with:
          node-version: '15'

      - name: Install application packages
        env:
          FONTAWESOME_NPM_AUTH_TOKEN: ${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}
        run: npm install

      - name: Build and release Electron app
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npm run electron:build